version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mealai-postgres
    environment:
      POSTGRES_DB: mealai
      POSTGRES_USER: mealai_user
      POSTGRES_PASSWORD: mealai_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mealai-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mealai.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:

